import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";

const roboto = Roboto({ subsets: ["latin"], weight: ["100", "400", "900"] });

export const metadata: Metadata = {
    title: "Bimtrazer Tech Test",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <NextUIProvider>
                    <div className="grid grid-cols-1 grid-rows-layout justify-center items-center align-middle w-full min-h-screen mx-auto bg-body overflow-hidden">
                        {children}
                    </div>
                </NextUIProvider>
            </body>
        </html>
    );
}
