import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Bimtrazer Tech Test",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NextUIProvider>
                    <div className="grid grid-cols-1 grid-rows-layout min-h-screen place-content-center">
                        {children}
                    </div>
                </NextUIProvider>
            </body>
        </html>
    );
}
